apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Rahul\react-gingonic-mysql\kompose-windows-amd64.exe --file .\docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "7070"
      port: 7070
      targetPort: 7070
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
