apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Rahul\react-gingonic-mysql\kompose-windows-amd64.exe --file .\docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: react
  name: react
spec:
  ports:
    - name: "3000"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: react
status:
  loadBalancer: {}

